#!/usr/bin/env python3

import sys
import textwrap
import re


class Markdown:
    """
    Markdown tools
    """
    re_heading = re.compile(r"^(#+)\s*(.*)$")

    def __init__(self, body):
        self.body = body

    def toc(self, ignore_headings=[], max_depth=None, links=True):
        """
        Generate a Table of Contents of the headings found in Markdown text.

        `ignore_headings` is a list of case-sensitive headings to ignore. E.g.
        "Table of Contents".

        `max_depth` defines the depth level of headings to include in the ToC. E.g.
        if `max_depth` is 2, headings `###` and deeper are not included. The
        default is `None`, which will include all headings.

        If `links` is True, links to the headings will be included, but whether
        they work depends on the Markdown renderer and Markdown text itself. They
        work with Github.
        """
        md_headings = []

        for line in self.body.splitlines():
            match = re.match(self.re_heading, line)
            if not match:
                continue

            heading_hash, title = match.groups()

            if title in ignore_headings:
                continue

            if max_depth is not None and len(heading_hash) > max_depth:
                continue

            str_indent = "    " * (len(heading_hash) - 1)
            str_href = title.replace(" ", "-").lower()
            if links is True:
                str_heading = f"* [{title}](#{str_href})"
            else:
                str_heading = f"* {title}"
            md_headings.append(
                str_indent + str_heading
            )

        return "\n".join(md_headings)


class TextError(Exception):
    pass


class Text:
    """
    Manipulate text using selection cursors.
    """
    def __init__(self, path):
        self.path = path
        with open(self.path, "r") as fh:
            self.content = fh.read()

        self.sel_start_pos = 0
        self.sel_end_pos = len(self.content)
        self.sel_start_text = None
        self.sel_end_text = None

    def _find(self, sub, start_pos=0):
        """
        Wrapper around `str.find()` that raises a TextError in case of
        problems.
        """
        pos = self.content.find(sub, start_pos)
        if pos == -1:
            raise TextError(f"Text not found after position {start_pos}: '{sub}'")

        return pos

    def sel(self, start=None, end=None, start_after=None, end_after=None):
        """
        Create a selection in the content.

        `start` sets the starting selection cursor to the beginning of the
        first occurance of `start`. To set the cursor to the end of the first
        occurance, use `start_after`.

        `end` sets the ending selection cursor to the beginning of the first
        occurance of `end` after the selection starting position. To set the
        cursor to the end of the first occurance, use `end_after`.

        If no end is provided, the ending selection cursor is set to the end of
        the starting selection.
        """
        if start is not None:
            self.sel_start_text = start
            self.sel_start_pos = self._find(start)
        elif start_after is not None:
            self.sel_start_text = start
            self.sel_start_pos = self._find(start_after) + len(start_after)

        if end is not None:
            self.sel_end_text = end
            self.sel_end_pos = self._find(end, self.sel_start_pos)
        elif end_after is not None:
            self.sel_end_text = end
            self.sel_end_pos = self._find(end_after, self.sel_start_pos) + len(end_after)
        else:
            # No end provided. Set it to end of start text
            self.sel_end_text = self.sel_start_text
            self.sel_end_pos = self.sel_start_pos + len(self.sel_start_text)

        return self

    def sel_start_fwd(self, start=None, start_after=None):
        """
        Forward the selection starting cursor to the beginning of the next
        `start`, or to the end of the next `start_after`.
        """
        if start is not None:
            self.sel_start_pos = self._find(start, self.sel_start_pos)
        elif start_after is not None:
            self.sel_start_pos = self._find(start, self.sel_start_pos) + len(start_after)

    def sel_end_fwd(self, end=None, end_after=None):
        """
        Forward the selection ending cursor to the beginning of the next `end`,
        or the end of the next `end_after`.
        """
        if end is not None:
            self.sel_end_pos = self._find(end, self.sel_end_pos)
        elif end_after is not None:
            self.sel_end_pos = self._find(end_after, self.sel_end_pos) + len(end_after)

        return self

    def insert_before(self, content):
        self.content = \
            self.content[:self.sel_start_pos] + \
            content + \
            self.content[self.sel_start_pos:]

        self.sel_start_pos += len(content)
        self.sel_end_pos += len(content)

        return self

    def insert_after(self, content):
        self.content = \
            self.content[:self.sel_end_pos] + \
            content + \
            self.content[self.sel_end_pos:]
        return self

    def replace(self, content):
        """
        Replace the current selection with `content`.
        """
        self.content = \
            self.content[:self.sel_start_pos] + \
            content + \
            self.content[self.sel_end_pos:]
        self.sel_end_pos = self.sel_start_pos + len(content)
        return self

    def delete(self):
        self.replace("")
        return self

    def extract(self):
        """
        Return contents of current selection.
        """
        return self.content[self.sel_start_pos:self.sel_end_pos]

    def result(self):
        return self.content

    def save(self, path=None):
        if path is None:
            path = self.path
        with open(path, "w") as fh:
            fh.write(self.content)
        return self

    def show_selection(self):
        return \
            self.content[:self.sel_start_pos] + \
            "\x1b[;93m{{{" + \
            self.content[self.sel_start_pos:self.sel_end_pos] + \
            "}}}\x1b[0m" + \
            self.content[self.sel_end_pos:]

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        pass


if __name__ == "__main__":
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r") as fh:
            code = fh.read()
    else:
        code = sys.stdin.read()

    vars = {
        "Markdown": Markdown,
        "Text": Text,
    }
    exec(code, vars)
